apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect
  template:
    metadata:
      labels:
        app: detect
    spec:
      containers:
      - name: detect
        image: detect:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MINIO_ENDPOINT
            value: "minio:9000"
          - name: MINIO_ACCESS_KEY
            value: "minioadmin"
          - name: MINIO_SECRET_KEY
            value: "minioadmin"
          - name: MINIO_BUCKET
            value: "images"
---
apiVersion: v1
kind: Service
metadata:
  name: detect
spec:
  selector:
    app: detect
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP