apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grayscale
  template:
    metadata:
      labels:
        app: grayscale
    spec:
      containers:
      - name: grayscale
        image: grayscale:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MINIO_ENDPOINT
            value: "minio:9000"
          - name: MINIO_ACCESS_KEY
            value: "minioadmin"
          - name: MINIO_SECRET_KEY
            value: "minioadmin"
          - name: MINIO_BUCKET
            value: "images"
---
apiVersion: v1
kind: Service
metadata:
  name: grayscale
spec:
  selector:
    app: grayscale
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP