apiVersion: apps/v1
kind: Deployment
metadata:
  name: resize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resize
  template:
    metadata:
      labels:
        app: resize
    spec:
      containers:
      - name: resize
        image: resize:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: MINIO_ENDPOINT
            value: "minio:9000"
          - name: MINIO_ACCESS_KEY
            value: "minioadmin"
          - name: MINIO_SECRET_KEY
            value: "minioadmin"
          - name: MINIO_BUCKET
            value: "images"
---
apiVersion: v1
kind: Service
metadata:
  name: resize
spec:
  selector:
    app: resize
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP